### ISSUE TITLE
Configure gradle build for multiple APKs.

### ISSUE THREAD

**Issue by IzzySoft** [City-Zouitel/JetNote#134]
The latest release added several proprietary libraries:

```
---------------
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Google App Engine (/com/google/appengine): NonFreeNet
* Cloud Audit Logs (/com/google/cloud/audit): Tracking
* Google Cloud Logging Client for Java (/com/google/cloud/logging): NonFreeNet
* Firebase (/com/google/firebase): NonFreeNet,NonFreeDep
* firebase-firestore (/com/google/firebase/firestore): NonFreeDep,NonFreeNet

6 offenders.
```

Further, APK size is now well beyond the limits of my repo (which is 30 MB per app). So could you please:

* provide the APK of a build flavor that comes without those proprietary libraries
* enable per-ABI builds to get the size down (I'd then pick either the armeabi of arm64 build, depending on your preference)

Until then, I'll now revert back to v3.2.0 in my repo and disable updates. Thanks in advance for your help!

**Comment by youndon** [comment]
Hi **IzzySoft** thank you for your report, I didn't know about the 30MB limits, Also I'll try to do your suggestion for the `per-ABI` one, And I will come up with a new release.

**Comment by IzzySoft** [comment]
Thanks for your prompt response! I'll try to be as fast once you report I can re-enable updates :smiley:

**Comment by youndon** [comment]
Well, I have released new three **APKs** (`armeabi-v7a`, `x86 `and `x86_64`).
For me, armeabi is my usual **APK**,
And I wondering if it's ok to put the three APKs together in the same release, 
Or it's fine even if add `arm64-v8a` supported **APK** ??

**Comment by IzzySoft** [comment]
> And I wondering if it's ok to put the three APKs together in the same release,

As long as the APK's have "stable names", you can attach as many as you want – I can set my updater to RegEx-match the one needed. You could e.g. use `JetNote-armeabi.apk` and `JetNote-arm64.apk`, and I'd tell my updater to only consider `/armeabi/i`, so it would ignore all others.

> Or it's fine even if add arm64-v8a supported APK ??

As pointed out: yes, it's fine. Just let me know which one I shall pick, and keep the naming conventions up between releases (so the RegEx keeps working).

> For me, armeabi is my usual APK,

OK, so let's take a look at that:

```
Offending libs:
---------------
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Google App Engine (/com/google/appengine): NonFreeNet
* Cloud Audit Logs (/com/google/cloud/audit): Tracking
* Google Cloud Logging Client for Java (/com/google/cloud/logging): NonFreeNet
* Firebase (/com/google/firebase): NonFreeNet,NonFreeDep
* firebase-firestore (/com/google/firebase/firestore): NonFreeDep,NonFreeNet

6 offenders.
```

Those are still there (were added with the previous release). Can we get rid of them, so it's FLOSS again? With those included, your app is no longer FOSS (as it contains proprietary parts). Plus I'd have to add 3 AntiFeatures, which would scare most FOSS-folks away. I guess removing Cloud Audit would get rid of all 6, though I'm not sure about Firestore.

**Comment by youndon** [comment]
Ok, If I understand you correctly, there serious issue in my google cloud service and it's FLOSS, And I should drop it to be FOSS right,
I really would just tell me If there alternative service I could use, because it's a big step back, I mean It's google you know how hard to get something similar.

**Comment by IzzySoft** [comment]
Oops, sorry for the misnomer: FLOSS (Free/Libre Open Source) and FOSS (Free Open Source) were meant synonymously. But yes, those libraries make it non-free. What features do you need? I'm pretty sure there are proper replacements, [see e.g. here](https://gitlab.com/-/snippets/1896503#firebase-per-se). Firestore could be replaced by [appwrite](https://github.com/appwrite/appwrite) or [Supabase](https://supabase.com/), for example. Not sure what you need Cloud Audit for, maybe the two can take care for that as well; if note, some of the other bug reporting libraries behind the link might fit.

**Comment by youndon** [comment]
Yes I see, And I respect your concern for user privacy, I will switch to **Supabase** as it seems like the big **Firebase** competitor, Until then I'll release a new one without **Google** service.
