### ISSUE TITLE
question on dependencies

### ISSUE THREAD

**Issue by IzzySoft** [City-Zouitel/JetNote#139]
Running Apktool over your APK, I see there are some libraries in which I cannot pin-point (cannot find the sources, but neither find them referenced directly here in your repo). Do you have any idea where they are coming from, and ideally can point me to their respective repositories?

```
/com/google/firebase/appcheck/interop:
/firebase/com/protolitewrapper:
/com/google/api:
/com/google/cloud/datastore/core/number:
/com/google/firebase/appcheck/interop:
/com/google/firestore/admin/v1:
/com/google/firestore/bundle:
/com/google/firestore/v1:
/com/google/geo/type:
/com/google/longrunning:
/com/google/rpc/context:
/com/google/type:
/firebase/com/protolitewrapper:
```

If you don't know either, maybe `gradle :app:dependencies` can help showing what drags them in. At least Firestore and Firebase look a bit problematic, as those are not really free (in the sense of "libre"). Thanks in advance for your help!

**Comment by youndon** [comment]
Yes, there was a lot of mess in that release, I use to fix it now in my last release, So check it and tell me if we fine.

**Comment by IzzySoft** [comment]
I thought you could tell me which libraries those strings belong to, and (if possible) a link to their source repos :see_no_evil: But from a look at their names, getting rid of them of course is even better – and gone they are: looking at the armeabi build, it seems clean now. Is there no universal build anymore? And no arm64 either? Does that mean I shall switch to the armeabi one for my repo – or did you just forget attaching the arm64 build? And was it intended to be a debug build?

I'm putting up the armeabi for now, we can adjust later. But as the native libs do only take up little space, there would not be that much a difference in size I guess; what size would we get at with a full universal build, and what with a full arm one?

**Comment by youndon** [comment]
> : looking at the armeabi build, it seems clean now. 

Great, We can move on, and I am also happy with this.

> Is there no universal build anymore? And no arm64 either?

I edit my last release and it includes `arm64` apk, And `universal` apk it could be available just tell me if you want me to upload it when you know its size can get over `38 MB`.

> and what with a full arm one?

I release only the full version of the apk, Cause there is a number of  screen densities(`ldpi`, `xxhdpi`, `xxxhdpi` ext).

**Comment by IzzySoft** [comment]
> universal apk it could be available just tell me if you want me to upload it when you know its size can get over 38 MB.

Oh, OK – that answers the question. I was hoping it might be "just around 30 MB" (I wouldn't argue a single MB, but at 32 MB we hit some API limit).

So OK, shall I switch to the arm64 build then? Or do we stay with armeabi? I'd leave this choice to you (btw, with "full arm one" I meant an APK with armeabi and arm64, but nothing else – but that might be a bit tricky to set up and, I assume, come pretty close to or beyond the 30 MB limit then).

**Comment by youndon** [comment]
Well, I guess most devices run on arm64 this days, So yah let's be `arm64` abi in instead of `armeabi`.
And there are no more `x84` and `x84_64` apk's.

**Comment by IzzySoft** [comment]
As you wish. Side-note: While most arm64 devices can run armeabi APKs (only exception known to me is the Pixel 7 plus), the opposite cannot be said. But then, to my experience, given the size of the APK I doubt it would run "really performant" on any of the "left-over" armeabi devices (in my test cases things started to get slow around 15..20MB APK size), so 64bit should be fine.

I've adjusted the config for my updater right now, so with future releases it will pull the 64bit APK. Should you want me to replace it "right now" just tell me and I'll see to it.

**Comment by youndon** [comment]
Yes, This is what I'm saying move on with 64bit.
