### ISSUE TITLE
APK available?

### ISSUE THREAD

**Issue by IzzySoft** [City-Zouitel/JetNote#22]
Is the APK available somewhere for download (maybe you could attach it to the corresponding releases)?

**Comment by youndon** [comment]
OK, I didn't publish this app into any store yet, But I put an [apk ](https://github.com/City-Zouitel/JetNote/blob/main/apks/JetNote_v1_6_3.apk)file v1.6.3 (lasts) in **apks** folder.

**Comment by IzzySoft** [comment]
Thanks, that works as well – but wouldn't it be better attached to its corresponding [release](https://github.com/City-Zouitel/JetNote/releases), so it doesn't "bloat" the repo itself? Also, looking at it, I see a minor issue (which will cause you trouble when trying to add it to a store):

    package: name='com.example.jetnote' versionCode='1' versionName='1.6.3'

You still have `versionCode: 1` despite of multiple releases. `versionCode` is what Android (and stores) use to tell versions apart, so you should increase it with each release. Could you please take care for that? Thanks!

**Comment by youndon** [comment]
Wow, you look understand the releases and publishing stuff, I didn't know about `versionCode `and `versionName `issue but I get your point here and I'll see what to do, But what you mean by "bloat the repo itself" in your comment, I normally release new `zip `file every bug fix or new feature add.

**Comment by IzzySoft** [comment]
> But what you mean by "bloat the repo itself"

If you add the APK (a big binary) via Git to your repo, it becomes part of your repo. So each and every contributor, when forking/cloning the repo to work on your code, needs to clone that binary along. Now comes the next release, and another binary. And again. All the old APKs are no longer relevant, but still part of your "code base" – so your contributors need to check them out needlessly.

Now if you instead attach the APK to its corresponding release, that's not part of the repo itself (only the tag is, not what's attached to releases). So your repo stays slim, your contributors happily clone a decently sized repo, and all are happy. What's more, to add the 3rd win: guess where people usually look first for a "release APK"? Yupp, at the releases :wink: So a clear win-win-win.

That said: wanna number 4? (quoting Queen: "Don't. Stop. Me. Now…") Thanks to your making the APK available, your app just showed up [in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.example.jetnote), making it easier for folks to discover it and keep it updated (the latter once you start increasing `versionCode`, as their clients only notify them when an APK with a higher `versionCode` than the one installed on-device is available; new releases are looked for daily by my updater, which can handle the APK inside your repo but also prefers it at the release). Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme if you wish. And should you have a dedicated icon for the app (currently it uses the default "Green Andy"), I'll happily add that to the listing. And provide you the Metadata in [Fastlane format](https://gitlab.com/-/snippets/1895688) if you wish, so you can control how your app is presented.

Oh – guess I just made obvious why I'm a bit familiar with "releases and publishing stuff": I'm running that repo for about 7 years now :wink:

**Comment by youndon** [comment]
Oh man I should pay you for that, Now I get it and I did change `versionCode` and `versionName` like you suggested and I pushed the app [apk](https://github.com/City-Zouitel/JetNote/releases/tag/v1.6.4) beside the zip releases as tag which I recommend you to use instead of repo one.
Also I'll put your badge soon as possible.

One last question: How I can create the update notify when new release come out (`versionCode`)??
Thank you so mutch.

**Comment by IzzySoft** [comment]
> Oh man I should pay you for that

:rofl: Donations are of course [always welcome](https://android.izzysoft.de/help?topic=support_us) – but advice was freely given. And thanks for adding the APK to the release: I've updated the config here to check the tag now.

> Also I'll put your badge soon as possible.

I see the badge already, wonderful – but could you link it to `https://apt.izzysoft.de/fdroid/index/apk/com.example.jetnote` instead of to the image source – so potential new users can follow up?

> How I can create the update notify when new release come out

You tag a new release and attach the APK to it. My updater checks once a day if new tags are available and if so, grabs the APK to publish it in my repo.

So now only the icon is missing. And my offer to send you the metadata via PR still stands then.

**Comment by IzzySoft** [comment]
> When going for a store you'll probably have to rebrand.

Ah, I see you just did. So please rather link to `https://apt.izzysoft.de/fdroid/index/apk/city.zouitel.jetnote` (renamed it here accordingly as my updater notified me, change will take effect with the next sync tomorrow).
